sudo: false

jdk:
    - openjdk8
    - oraclejdk8

before_install:
    # Get a newer version of maven
    - wget http://mirrors.ibiblio.org/apache/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
    - tar -xzf apache-maven-3.5.4-bin.tar.gz
    - mv apache-maven-3.5.4/ apache-maven/
    - echo 'export JAVA_HOME=/usr/lib/jvm/java-8-oracle' >> ~/.bashrc
    - echo 'export M2_HOME=${HOME}/apache-maven' >> ~/.bashrc
    - echo 'export MAVEN_HOME=${HOME}/apache-maven' >> ~/.bashrc
    - echo 'export PATH=${M2_HOME}/bin:${PATH}' >> ~/.bashrc
    - source ~/.bashrc

install:
    - $HOME/apache-maven/mvn clean install

script:
    - $HOME/apache-maven/mvn clean install

